name: TM-pipeline
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _r-mutex=1.0.1
  - anyio=4.9.0
  - appspam=1.03
  - argcomplete=3.6.2
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.44
  - bioconductor-ggtree=3.14.0
  - bioconductor-ggtreeextra=1.16.0
  - bioconductor-treeio=1.30.0
  - bleach=6.2.0
  - brotlicffi=1.1.0.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cairo=1.18.4
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - cpp-expected=1.1.0
  - curl=8.14.1
  - debugpy=1.8.15
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gappa=0.9.0
  - gcc_impl_linux-64=15.1.0
  - gfortran_impl_linux-64=15.1.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7.1
  - gxx_impl_linux-64=15.1.0
  - h11=0.16.0
  - harfbuzz=11.2.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jq=1.8.1
  - json5=0.12.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libarchive=3.8.1
  - libblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgit2=1.8.4
  - libglib=2.84.1
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.3.0
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsanitizer=15.1.0
  - libsodium=1.0.20
  - libsolv=0.7.34
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - make=4.4.1
  - mamba=2.3.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mpi=1.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - niemads=1.0.16
  - nlohmann_json=3.11.3
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - oniguruma=6.9.10
  - openmpi=4.1.6
  - openssl=3.5.1
  - overrides=7.7.0
  - packaging=25.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=3.2.1
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - r-ape=5.8_1
  - r-aplot=0.2.8
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-bms=0.3.5
  - r-boot=1.3_31
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-broom=1.0.8
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-caret=6.0_94
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=2.0.0
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.2
  - r-crul=1.5.0
  - r-curl=6.2.2
  - r-data.table=1.17.6
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-diffobj=0.3.6
  - r-digest=0.6.37
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-essentials=4.4
  - r-evaluate=1.0.4
  - r-extrafont=0.19
  - r-extrafontdb=1.0
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_90
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-future=1.58.0
  - r-future.apply=1.20.0
  - r-gargle=1.5.2
  - r-generics=0.1.4
  - r-gert=2.1.4
  - r-ggfun=0.2.0
  - r-ggnewscale=0.5.2
  - r-ggplot2=3.5.2
  - r-ggplotify=0.1.2
  - r-ggstar=1.0.4
  - r-gh=1.5.0
  - r-gistr=0.9.0
  - r-gitcreds=0.1.2
  - r-glmnet=4.1_10
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gridgraphics=0.5_1
  - r-gtable=0.3.6
  - r-hardhat=1.4.1
  - r-haven=2.5.4
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-httr2=1.2.0
  - r-ids=1.0.1
  - r-ini=0.3.1
  - r-ipred=0.9_15
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lobstr=1.1.2
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-maps=3.4.3
  - r-mass=7.3_64
  - r-matrix=1.7_3
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-parallelly=1.45.0
  - r-pastecs=1.4.2
  - r-patchwork=1.3.1
  - r-pbdzmq=0.3_14
  - r-pillar=1.11.0
  - r-pkgbuild=1.4.8
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.3
  - r-pkgload=1.4.0
  - r-plyr=1.8.9
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.6
  - r-prodlim=2025.04.28
  - r-profvis=0.4.0
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.2
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-quantmod=0.4.28
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-randomforest=4.7_1.2
  - r-rappdirs=0.3.3
  - r-rbokeh=0.5.2
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcppeigen=0.3.4.0.2
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-recipes=1.3.1
  - r-recommended=4.4
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-repr=1.1.7
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-roxygen2=7.3.2
  - r-rpart=4.1.24
  - r-rprojroot=2.1.0
  - r-rstudioapi=0.17.1
  - r-rttf2pt1=1.3.12
  - r-rversions=2.1.2
  - r-rvest=1.0.4
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.3
  - r-shape=1.4.6.1
  - r-shiny=1.11.1
  - r-sourcetools=0.1.7_1
  - r-sparsevctrs=0.3.4
  - r-spatial=7.3_18
  - r-squarem=2021.1
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-testthat=3.2.3
  - r-textshaping=1.0.1
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidytree=0.4.6
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-tinytex=0.57
  - r-triebeard=0.4.1
  - r-ttr=0.24.4
  - r-tzdb=0.5.0
  - r-urlchecker=1.0.1
  - r-urltools=1.7.3
  - r-usethis=3.1.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.6.2
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml2=1.3.8
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-xts=0.14.1
  - r-yaml=2.3.10
  - r-yulab.utils=0.2.0
  - r-zip=2.3.3
  - r-zoo=1.8_14
  - raxml-ng=1.2.2
  - readline=8.2
  - referencing=0.36.2
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.26.0
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - simdjson=3.13.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - sysroot_linux-64=2.28
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - traitlets=5.14.3
  - treecluster=1.0.4
  - treeshrink=1.3.9
  - treeswift=1.1.45
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - urllib3=2.5.0
  - veryfasttree=4.0.5
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - xmltodict=0.14.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - configparser==7.2.0
    - cvxopt==1.3.2
    - cython==3.1.2
    - dendropy==5.0.8
    - fastroot==1.5
    - numpy==2.3.1
    - tqdm==4.67.1
    - witch-msa==1.0.9
